apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels: 
    name: mysql
spec: 
  containers: 
    - image: mysql
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysqlrootpassword
        - name: MYSQL_DATABASE
          value: ghost
        - name: MYSQL_USER
          value: ghost_user
        - name: MYSQL_PASSWORD
          value: ghost_pass
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-vol
          mountPath: /var/lib/mysql
      livenessProbe:
        tcpSocket:
          port: "mysql"
        initialDelaySeconds: 5
        timeoutSeconds: 1
      readinessProbe:
        exec:
          command: ["mysqladmin", "status", "-pmysqlrootpassword"]
  volumes:
    - name: mysql-vol
      hostPath:
        path: /var/lib/mysql
